language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

# Notify Gitter
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/304d4a2a461f862ce3a7
    on_success: always
    on_failure: always
    on_start: always
